
server:
  port: 8500
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/note
    password: celal371
    username: postgres
    platform: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          validation:
            mode: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 100
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

